on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: get dependencies
        run: yarn
      - name: execute tests
        run: yarn jest
